apiVersion: v1
kind: Namespace
metadata:
  name: user-app1

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-svc-deployment
  namespace: user-app1
spec:
  selector:
    matchLabels:
      app: spring-boot-k8s
  replicas: 4
  template:
    metadata:
      labels:
        app: spring-boot-k8s
    spec:
      containers:
        - name: userapp-app-container
          image: 'soni05ra/user-service:1.0.0-6'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9091

---

apiVersion: v1
kind: Service
metadata:
  name: userapp-service
  namespace: user-app1
spec:
  selector:
    app: spring-boot-k8s
  ports:
    - protocol: TCP
      port: 9091
      targetPort: 9091
  type: NodePort
